name: Merge Workflows

on:
  workflow_dispatch:
    inputs:
      Tag:
        description: The git tag name to pass to the Python and PowerShell scripts.
        required: true
        type: string
        
env:
  COMMIT_ID: ${{ github.sha }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: GetCommitId
        run: |
          pwsh -File ./.github/workflows/getcommitid.ps1 -SourceTag ${{ inputs.Tag }}
        #echo "COMMIT_ID=$commitid" >> $GITHUB_ENV
        shell: pwsh
     
      - name: print commit id
        run: echo "COMMIT ID IS ${{ env.COMMIT_ID }}"

  prod:
    runs-on: ubuntu-latest
    needs: release
    #needs: [release, approval]
    #if: ${{ needs.approval.outputs.approval == 'approved' }}
    steps:
      - uses: actions/checkout@v3

      - name: Merging repo
        run: |
          pwsh -File ./.github/workflows/getcommitid.ps1 -SourceTag ${{ inputs.Tag }}
        shell: pwsh
     
      - name: printING commit id  
        run: echo "COMMIT ID IS ${{ env.COMMIT_ID }}"
